### PR TITLE
Fit NeRO for Blender Dataset; Add dataset_dir in config files;

### PR DESCRIPTION
**Pull request by ingra14m**

### CODE REVIEW

**Comment by liuyuan-pal** [comment]
Thank you very much for your contribution for adding support for the nerf-blender datasets!
Would you mind if I update it to another branch and mention it in the markdown?

**Comment by ingra14m** [comment]
Thank you for your appreciation. I am glad to hear that my contribution towards adding support for the blender datasets has been beneficial.

As for your request, I have no objections at all. Feel free to update it to another branch. I'll write a README right now.

**Comment by ingra14m** [comment]
I have already add README for running the Blender Dataset. This branch is compatible with the original NeRO dataset.

**Comment by liuyuan-pal** [comment]
Hi, it seems that there are some conflicts here so I cannot merge and rebase it to another branch. Maybe, you need to pull my updates and resolve them. I didn't update any essential codes yet.

**Comment by ingra14m** [comment]
Hi, I have already pull your updates in the main branch before. The pull request step shows that there are no conflicts and it can be merged. How can I help you with the merge?
image

**Comment by liuyuan-pal** [comment]
Hi, I've figured out how to merge into another branch. Thanks for your efforts!

**Pull request merged**
